package java.lang;

// generated by: scripts/buildjcl.luau
public class ArrayIndexOutOfBoundsException extends IndexOutOfBoundsException {
    public ArrayIndexOutOfBoundsException() { super(); }
    public ArrayIndexOutOfBoundsException(String message) { super(message); }
    public ArrayIndexOutOfBoundsException(String message, Throwable cause) { super(message, cause); }
}
