package java.lang;

// generated by: scripts/buildjcl.luau
public class AssertionError extends Error {
    public AssertionError() { super(); }
    public AssertionError(String message) { super(message); }
    public AssertionError(String message, Throwable cause) { super(message, cause); }
}
