package java.lang;

// generated by: scripts/buildjcl.luau
public class ClassCastException extends RuntimeException {
    public ClassCastException() { super(); }
    public ClassCastException(String message) { super(message); }
    public ClassCastException(String message, Throwable cause) { super(message, cause); }
}
