package java.lang;

// generated by: scripts/buildjcl.luau
public class Error extends Throwable {
    public Error() { super(); }
    public Error(String message) { super(message); }
    public Error(String message, Throwable cause) { super(message, cause); }
}
