package java.lang;

// generated by: scripts/buildjcl.luau
public class Exception extends Throwable {
    public Exception() { super(); }
    public Exception(String message) { super(message); }
    public Exception(String message, Throwable cause) { super(message, cause); }
}
