package java.lang;

// generated by: scripts/buildjcl.luau
public class IllegalStateException extends RuntimeException {
    public IllegalStateException() { super(); }
    public IllegalStateException(String message) { super(message); }
    public IllegalStateException(String message, Throwable cause) { super(message, cause); }
}
