package java.lang;

// generated by: scripts/buildjcl.luau
public class IndexOutOfBoundsException extends RuntimeException {
    public IndexOutOfBoundsException() { super(); }
    public IndexOutOfBoundsException(String message) { super(message); }
    public IndexOutOfBoundsException(String message, Throwable cause) { super(message, cause); }
}
