package java.lang;

// generated by: scripts/buildjcl.luau
public class LinkageError extends Error {
    public LinkageError() { super(); }
    public LinkageError(String message) { super(message); }
    public LinkageError(String message, Throwable cause) { super(message, cause); }
}
