package java.lang;

// generated by: scripts/buildjcl.luau
public class NoClassDefFoundError extends LinkageError {
    public NoClassDefFoundError() { super(); }
    public NoClassDefFoundError(String message) { super(message); }
    public NoClassDefFoundError(String message, Throwable cause) { super(message, cause); }
}
