package java.lang;

// generated by: scripts/buildjcl.luau
public class NullPointerException extends RuntimeException {
    public NullPointerException() { super(); }
    public NullPointerException(String message) { super(message); }
    public NullPointerException(String message, Throwable cause) { super(message, cause); }
}
