package java.lang;

// generated by: scripts/buildjcl.luau
public class OutOfMemoryError extends VirtualMachineError {
    public OutOfMemoryError() { super(); }
    public OutOfMemoryError(String message) { super(message); }
    public OutOfMemoryError(String message, Throwable cause) { super(message, cause); }
}
