package java.lang;

// generated by: scripts/buildjcl.luau
public class RuntimeException extends Exception {
    public RuntimeException() { super(); }
    public RuntimeException(String message) { super(message); }
    public RuntimeException(String message, Throwable cause) { super(message, cause); }
}
