package java.lang;

// generated by: scripts/buildjcl.luau
public class StackOverflowError extends VirtualMachineError {
    public StackOverflowError() { super(); }
    public StackOverflowError(String message) { super(message); }
    public StackOverflowError(String message, Throwable cause) { super(message, cause); }
}
