package java.lang;

// generated by: scripts/buildjcl.luau
public class UnsupportedOperationException extends RuntimeException {
    public UnsupportedOperationException() { super(); }
    public UnsupportedOperationException(String message) { super(message); }
    public UnsupportedOperationException(String message, Throwable cause) { super(message, cause); }
}
