package java.lang;

// generated by: scripts/buildjcl.luau
public class VirtualMachineError extends Error {
    public VirtualMachineError() { super(); }
    public VirtualMachineError(String message) { super(message); }
    public VirtualMachineError(String message, Throwable cause) { super(message, cause); }
}
